---

- name: This is a hello-world example
  hosts: localhost
  gather_facts: false
  vars_files:
    - secrets.yml

  pre_tasks:
    - name: Login to oVirt
      ovirt_auth:
        hostname: ovirt-engine.europe.intranet
        username: "{{ oVirt.username }}"
        password: "{{ oVirt.password }}"

  tasks:
  - name: Run VM with cloud init
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      name: teste
      template: CentOS7
      cluster: Default
      instance_type: Small
      cloud_init:
        nic_boot_protocol: dhcp
        dns_search: europe.intranet
        dns_servers:
          - 192.168.1.100
        nic_name: eth0
        nic_on_boot: true
        host_name: teste.europe.intranet
        custom_script: |
          runcmd:
            - yum update -y
        user_name: root
        root_password: "{{ oVirt.password }}"

  - name: Migrate/Run VM to/on host named 'host1'
    ovirt_vm:
      auth: "{{ ovirt_auth }}"
      state: running
      name: teste

  post_tasks:
    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
